version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: conan config install .conan --type dir
      - run: conan create . 0.0.0@tradingview/testing --profile x86_64-Windows-v142-Release
