version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: conan create . 0.0.0.0@tradingview/testing -s compiler.cppstd=17
